name: Salesforce Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Authenticate to Salesforce using Auth URL
        run: echo "${{ secrets.SF_AUTH_URL }}" > sfdx_auth_url.txt && sfdx auth:sfdxurl:store --sfdxurlfile sfdx_auth_url.txt --setalias MyDevOrg --setdefaultusername

      - name: Run Apex tests (Synchronous)
        run: sfdx force:apex:test:run --result-format human --code-coverage --output-dir test-result --wait 10

      - name: Test Coverage Report
        run: sfdx force:apex:test:report --codecoverage --outputdir test-result

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install @salesforce/cli --global

      - name: Authenticate to Salesforce using Auth URL
        run: echo "${{ secrets.SF_AUTH_URL }}" > sfdx_auth_url.txt && sfdx auth:sfdxurl:store --sfdxurlfile sfdx_auth_url.txt --setalias MyDevOrg --setdefaultusername

      - name: Deploy to Salesforce (Simulated)
        run: echo "Deploying to Salesforce..."
